CREATE TABLE GOODLIKE( -- 좋아요
	LIKE_NUM INT PRIMARY KEY, -- 번호 PK
	LIKE_BOARD_NUM INT, -- 좋아요 받은 글 FK
	LIKE_MEMBER_ID VARCHAR(100) NOT NULL -- 좋아요 누른 사람 FK
);
-- 테이블 삭제
DROP TABLE GOODLIKE;
-- 전체 출력
SELECT * FROM GOODLIKE;

-- FK 제약조건
ALTER TABLE GOODLIKE -- GOODLIKE 테이블 변경할거야.
ADD CONSTRAINT FK_LIKECONTENTS --좋아요 받은 글
FOREIGN KEY (LIKE_BOARD_NUM) -- LIKECONTENTS가 FK (좋아요 받은 글)
REFERENCES BOARD(BOARD_NUM) -- BOARDNUM
ON DELETE CASCADE; -- 원본 데이터(글 삭제시) 데이터 삭제

-- 제약조건 삭제
ALTER TABLE GOODLIKE
DROP CONSTRAINT FK_LIKECONTENTS;

-- 제약조건 확인
SELECT constraint_name
FROM user_constraints
WHERE table_name = 'GOODLIKE' AND constraint_type = 'R';


ALTER TABLE GOODLIKE
ADD CONSTRAINT FK_LIKEMEMBER -- 좋아요 누른 사람
FOREIGN KEY (LIKE_MEMBER_ID)
REFERENCES MEMBER(MEMBER_ID) -- MEMBER테이블의 MID
ON DELETE CASCADE; -- 원본 데이터(회원 탈퇴시) 데이터 삭제

-- 샘플 데이터
INSERT INTO GOODLIKE VALUES(COALESCE((SELECT MAX(LIKE_NUM) FROM GOODLIKE),0)+1,7,'wlsrja3852@naver.com');
INSERT INTO GOODLIKE VALUES(COALESCE((SELECT MAX(LIKE_NUM) FROM GOODLIKE),0)+1,7,'MOOGUN@naver.com');


SELECT * FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SYS_C008177';