CREATE TABLE WISHLIST( -- 찜
   WISHLIST_NUM INT PRIMARY KEY, -- 번호 PK
   WISHLIST_MEMBER_ID VARCHAR(255) NOT NULL, -- 사용자 ID FK
   WISHLIST_PRODUCT_NUM INT NOT NULL -- 상품 번호 FK
);


-- 테이블 삭제
DROP TABLE WISHLIST;
-- 전체 출력
SELECT * FROM WISHLIST;

--컬럼 타입 변경
ALTER TABLE WISHLIST
MODIFY WISHLIST_MEMBER_ID VARCHAR(255);

-- 컬럼 확인
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'WISHLIST';

-- 샘플
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',9);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',10);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',13);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',18);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',28);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'wlsrja3852@naver.com',9);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'wlsrja3852@naver.com',3);

INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',23);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',25);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',23);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',19);
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,'tlsektha3852@naver.com',17);


-- FK 제약조건 (멤버)
ALTER TABLE WISHLIST -- WISHLIST 테이블 변경
ADD CONSTRAINT FK_WISHLIST_MEMBER_ID -- FK 제약조건 추가
FOREIGN KEY (WISHLIST_MEMBER_ID) -- FK키는 WISHLIST_MEMBER_ID
REFERENCES MEMBER(MEMBER_ID) -- FK키는 MEMBER테이블의 MEMBER_ID 컬럼에 의존
ON DELETE CASCADE; -- 회원이 탈퇴하면 위시리스트도 함께 삭제

-- FK 제약조건 (상품)
ALTER TABLE WISHLIST -- WISHLIST 테이블 변경
ADD CONSTRAINT FK_WISHLIST_PRODUCT_NUM -- FK 제약조건 추가
FOREIGN KEY (WISHLIST_PRODUCT_NUM) -- FK키는 WISHLIST_PRODUCT_NUM
REFERENCES PRODUCT(PRODUCT_NUM) -- FK키는 PRODUCT테이블의 PRODUCT_NUM 컬럼에 의존
ON DELETE CASCADE; -- 상품이 삭제되면 위시리스트에서도 함께 삭제


-- 위시리스트 추가
INSERT INTO WISHLIST (WISHLIST_NUM,WISHLIST_MEMBER_ID,WISHLIST_PRODUCT_NUM) VALUES (COALESCE((SELECT MAX(WISHLIST_NUM) FROM WISHLIST),0)+1,?,?);

-- 위시리스트 삭제
DELETE FROM WISHLIST WHERE WISHLIST_NUM = ?;

-- 내 위시리스트 전체 보기
-- 위시리스트 번호 / 상품번호 / *상품명 / *상품가격 / *상품 장소(바다,민물) / *상품 유형(낚시배,낚시터,낚시카페,수상) / *상품주소 / *파일명 / *파일확장자 / *파일경로
SELECT WD.WISHLIST_NUM, WD.WISHLIST_PRODUCT_NUM, WD.PRODUCT_NAME, WD.PRODUCT_PRICE, WD.PRODUCT_LOCATION, WD.PRODUCT_CATEGORY, WD.PRODUCT_ADDRESS, WD.FILE_NAME, WD.FILE_EXTENSION, WD.FILE_DIR
FROM (SELECT W.WISHLIST_NUM, W.WISHLIST_PRODUCT_NUM, P.PRODUCT_NAME, P.PRODUCT_PRICE, P.PRODUCT_LOCATION, P.PRODUCT_CATEGORY, P.PRODUCT_ADDRESS, I.FILE_NAME, I.FILE_EXTENSION, I.FILE_DIR,
			ROW_NUMBER() OVER(ORDER BY WISHLIST_NUM DESC)AS ROW_NUM
	FROM WISHLIST W
	JOIN PRODUCT P ON W.WISHLIST_PRODUCT_NUM = P.PRODUCT_NUM
	LEFT JOIN (SELECT FILE_NAME, FILE_EXTENSION, FILE_DIR, PRODUCT_ITEM_NUM, ROW_NUMBER() OVER(PARTITION BY PRODUCT_ITEM_NUM ORDER BY FILE_NUM)AS RN FROM IMAGEFILE)I
	ON P.PRODUCT_NUM = I.PRODUCT_ITEM_NUM AND I.RN=2
	WHERE WISHLIST_MEMBER_ID = ?) WD
WHERE ROW_NUM BETWEEN (COALESCE(?,1)-1)*9+1 AND COALESCE(?,1)*9;


-- 위시리스트 개수 반환
SELECT COUNT(WISHLIST_NUM) AS WISHLIST_COUNT FROM WISHLIST WHERE WISHLIST_MEMBER_ID=?;


-- 위시리스트 페이지네이션 / 전체 페이지 수 반환
SELECT CEIL(COUNT(WISHLIST_NUM)/9.0)AS WISHLIST_TOTAL_PAGE FROM WISHLIST WHERE WISHLIST_MEMBER_ID=?;




